export const MODAL_ACTION_OPEN = "MODAL_ACTION_OPEN";
export const MODAL_ACTION_CLOSE = "MODAL_ACTION_CLOSE";
export const MODAL_SETTING_OPEN = "MODAL_SETTING_OPEN";
export const MODAL_SETTING_CLOSE = "MODAL_SETTING_CLOSE";
export const MODAL_DELETE_OPEN = "MODAL_DELETE_OPEN";
export const MODAL_DELETE_CLOSE = "MODAL_DELETE_CLOSE";
export const MODAL_UNFOLLOW_OPEN = "MODAL_UNFOLLOW_OPEN";
export const MODAL_UNFOLLOW_CLOSE = "MODAL_UNFOLLOW_CLOSE";
